name: Super-Linter

on:
  push:
  pull_request:


jobs:
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the event to run on
    runs-on: ubuntu-latest
    timeout-minutes: 60
   
    steps:
      
      # Checkout the code base
      
      - name: Checkout Code
        uses: actions/checkout@v3
        

      # Run Linter against code base #
      - name: Super-Linter
        uses: github/super-Linter@v4.9.5
        env:
           DEFAULT_BRANCH: main  
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         